### ISSUE TITLE
is there any instructions to generate counterfactual data?

### ISSUE THREAD

**Issue by dhx20150812** [eric11eca/disco#1]
Thank you for your nice work. It helps me a lot!

It would be better if there are some instructions or docs about how to reproduce your steps.

Thanks in advance.

**Comment by eric11eca** [comment]
Hi, thank you for your interest in our work! We are currently upgrading the codebase for the camera-ready submission. We will soon update the code and provide more detailed instructions.

**Comment by dhx20150812** [comment]
Is this paper accepted by ACL2023 ?

**Comment by eric11eca** [comment]
Yes, this paper was recently accepted by ACL2023.
